# Build and publish snapshot package when pushed to master

name: Publish Snapshot

on:
  push:
    branches:
      - master

env:
  JAVA_VERSION_TO_USE: '11'
  JAVA_DISTRI_TO_USE: 'corretto'
  REPORTSPATH:  '**/surefire-reports/TEST-*.xml'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ env.JAVA_VERSION_TO_USE }} (${{ env.JAVA_DISTRI_TO_USE }}) for build
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION_TO_USE }}
        distribution: ${{ env.JAVA_DISTRI_TO_USE }}
        cache: maven
        server-id: github
        server-username: dummy  # not used
        server-password: GITHUB_TOKEN_REF

    - name: Build with Maven
      run: mvn -B -Pgithub -Dmaven.test.failure.ignore=true package
      env:
          GITHUB_TOKEN_REF: ${{ secrets.GH_WORKFLOWS_PAT_READ_PACKAGES }}

    - name: Generate test summary
      uses: mikepenz/action-junit-report@v3.2.0
      if: always()
      with:
        report_paths: ${{ env.REPORTSPATH }}

    - name: Generate detailled report
      uses: dorny/test-reporter@v1.5.0
      if: always()
      with:
        name: JUnit Test Report (Details)
        path: ${{ env.REPORTSPATH }}
        reporter: java-junit

    - name: Set up JDK ${{ env.JAVA_VERSION_TO_USE }} (${{ env.JAVA_DISTRI_TO_USE }}) for publish
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION_TO_USE }}
        distribution: ${{ env.JAVA_DISTRI_TO_USE }}
        cache: maven

    - name: Publish to GitHub Packages
      run: mvn -B -Pgithub -DskipTests deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
